/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CorridaDeMotos;

public class App {
    
        public static void main (String[] args ){
            Moto Suzuki = new Moto(new MotorSuzuki());
            Moto Honda = new Moto(new MotorHonda());
            Moto Kawasaki = new Moto(new MotorKawasaki());
            
            System.out.println(Suzuki.acelerar());
            System.out.println(Honda.acelerar());
            System.out.println(Kawasaki.acelerar());
        }
}

    
